apiVersion: v1
kind: Service
metadata:
  name: mongo-lb
  namespace: dev
  labels:
    name: mongo
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      name: http
      targetPort: 27017
  selector:
    app: mongo
